/**
 * Time.
 *
 * Every deadline in this system is an absolute UTC timestamp generated by the
 * server. Clients render countdowns by subtracting from their own clock; the API
 * never sends "minutes remaining".
 *
 * The reason is operational rather than aesthetic: a yard's tablet with a wrong
 * system clock must not be able to argue about the 15 minutes. The server owns
 * time, and the only thing a client owns is the rendering of it.
 */

/** Add whole minutes to an instant, returning a new Date. */
export function addMinutes(from: Date, minutes: number): Date {
  return new Date(from.getTime() + minutes * 60_000);
}

/** Milliseconds from now until an absolute deadline; never negative. */
export function msUntil(deadline: Date, now: Date = new Date()): number {
  return Math.max(0, deadline.getTime() - now.getTime());
}

/** Whole seconds between two instants. */
export function secondsBetween(from: Date, to: Date): number {
  return Math.max(0, Math.round((to.getTime() - from.getTime()) / 1000));
}

/** ISO-8601 with an explicit Z. The only serialised form of an instant. */
export function toIsoUtc(d: Date): string {
  return new Date(d.getTime()).toISOString();
}

/**
 * Peak-hour classification for SLA reporting.
 *
 * The honest public promise is "typically 90 minutes, up to 3 hours in peak
 * traffic", so attainment has to be measurable split by which one applied. The
 * windows are evaluated in the market's own timezone and its own weekend days,
 * both of which are configuration.
 */
export interface PeakWindow {
  readonly startHour: number;
  readonly endHour: number;
}

export const DEFAULT_PEAK_WINDOWS: readonly PeakWindow[] = [
  { startHour: 7, endHour: 10 },
  { startHour: 16, endHour: 20 },
];

export function isPeak(
  at: Date,
  timezone: string,
  weekendDays: readonly number[],
  windows: readonly PeakWindow[] = DEFAULT_PEAK_WINDOWS,
): boolean {
  const parts = new Intl.DateTimeFormat('en-GB', {
    timeZone: timezone,
    hour: 'numeric',
    hour12: false,
    weekday: 'short',
  }).formatToParts(at);
  const hourPart = parts.find((p) => p.type === 'hour')?.value ?? '0';
  const weekdayPart = parts.find((p) => p.type === 'weekday')?.value ?? '';
  const hour = Number(hourPart) % 24;
  const weekdayIndex = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].indexOf(weekdayPart);
  if (weekendDays.includes(weekdayIndex)) return false;
  return windows.some((w) => hour >= w.startHour && hour < w.endHour);
}
